### ISSUE TITLE
Support save/load operation for all elements

### ISSUE THREAD

**Issue by ruochao** [mocircle/cidrawing#26]
All elements or objects (e.g. layer, board) should be able to save to file or other media, also it can be loaded again.

**Comment by vishmayleeway** [comment]
In page_layout.xml :  
<RelativeLayout
        android:id="@+id/reletive"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@id/bottom_layout"
        android:layout_below="@id/top2_layout"
        android:background="#ffffff">

        <com.mocircle.cidrawing.view.CiDrawingView
            android:id="@+id/drawing_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </RelativeLayout>
..........................................................
In MainActivity.java :
RelativeLayout reletive = (RelativeLayout) findViewById(R.id.reletive);

   public void save() {
        reletive.setDrawingCacheEnabled(true);
        reletive.buildDrawingCache();
        bitmap = reletive.getDrawingCache(true);
        String root = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).toString();
        System.out.println(root + " Root value in saveImage Function");
        File myDir = new File(root + "/" + getResources().getString(R.string.app_name));

        if (!myDir.exists()) {
            myDir.mkdirs();
        }

        Random generator = new Random();
        int n = 10000;
        n = generator.nextInt(n);
        iname = "Image-" + n + ".jpg";
        File file = new File(myDir, iname);
        if (file.exists())
            file.delete();
        try {
            FileOutputStream out = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.JPEG, 90, out);
            out.flush();
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        MediaScannerConnection.scanFile(getApplicationContext(), new String[]{file.toString()}, null,
                new MediaScannerConnection.OnScanCompletedListener() {
                    public void onScanCompleted(String path, Uri uri) {
                        Log.i("ExternalStorage", "Scanned " + path + ":");
                        Log.i("ExternalStorage", "-> uri=" + uri);
                    }
                });

        Image_path = Environment.getExternalStorageDirectory() + "/Pictures" + "/"
                + getResources().getString(R.string.app_name) + "/" + iname;

        File[] files = myDir.listFiles();
        numberOfImages = files.length;
        Toast.makeText(getApplicationContext(), "Saved", Toast.LENGTH_SHORT).show();
        System.out.println("Total images in Folder " + numberOfImages);
    }

**Comment by ruochao** [comment]
@vishmayleeway this issue is trying to add ability to save as file and then read it back, your suggestion is saving as picture, I will add file another bug to track this feature called it export as picture, thanks for comment.

**Comment by ruochao** [comment]
The way will be saving all elements including layer, etc as json file.

**Comment by ruochao** [comment]
https://github.com/mocircle/cidrawing/pull/28
