### ISSUE TITLE
Load Data not working properly

### ISSUE THREAD

**Issue by rashidabbas** [mocircle/cidrawing#35]
Hi, I am facing issue into load saved drawing feature.
I draw some shape then erase some part of shape after that I saved this drawing it saved successfully but when I reload this saved drawing the eraser path get removed from drawing and I am unable to load drawing with erased path drawing.

please help me to fix this issue.
thanks in advance

Best Regards,
Rashid Abbas

**Comment by faran-iqbal** [comment]
Hi @rashidabbas ,

I am also facing the same issue what you have reported.
Do you find any solution of that ?

I am using Ci Drawing Library, its amazing for sure.
I am facing a little bit problem with loadDrawing method.
What I am Doing ?
1- I draw some shape on Drawing View
2- Erase some path/points of that drawing
3- I Saved that drawing using saveDrawing Method
4- I called loadDrawing Method, It has an issue that the erase data got filled with black color.

I have then again tried this scenario in our sample app, the result is same there too.
Please fix this as soon as possible. Regardless this issue, everything is working fine in my case.

Regards,
Faran Iqbal.

**Comment by ruochao** [comment]
@rashidabbas @faran432  it's an issue, I will work on it.

**Comment by rashidabbas** [comment]
@ruochao thanks for response of my issue. I am too much excited to see this feature with no error.

Thanks

**Comment by ruochao** [comment]
@rashidabbas issue has been fixed by https://github.com/mocircle/cidrawing/commit/5dddc247d51e7ee49d499c1ba8747f72f79974d7

**Comment by faran-iqbal** [comment]
@ruochao  Thanks alot.

**Comment by ruochao** [comment]
Close issue
