### ISSUE TITLE
Load Data has an issue with erased drawing

### ISSUE THREAD

**Issue by faran-iqbal** [mocircle/cidrawing#36]
Hi, 
I am using **Ci Drawing** Library, its amazing for sure. 
I am facing a little bit problem with loadDrawing method. 
What I am Doing ?
1- I draw some shape on Drawing View
2- Erase some path/points of that drawing
3- I Saved that drawing using saveDrawing Method
4- I called loadDrawing Method, It has an issue that the erase data got filled with black color. 

I have then again tried this scenario in our sample app, the result is same there too.
Please fix this as soon as possible. Regardless this issue, everything is working fine in my case.

Regards,
Faran Iqbal.

**Comment by ruochao** [comment]
@faran432 issue has been fixed by https://github.com/mocircle/cidrawing/commit/5dddc247d51e7ee49d499c1ba8747f72f79974d7

**Comment by faran-iqbal** [comment]
@ruochao  Thanks man, Appreciate that.
